{% set name = "pygc" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygc-{{ version }}.tar.gz
  sha256: c43130425fb95c049a5fe93dfa007bf0f2dd8a538e1bf699d8e8b05d1f54715e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41.2
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pyproj

test:
  imports:
    - pygc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/axiom-data-science/pygc
  license: MIT
  license_file: LICENSE
  summary: Great Circle calculations in Python using Vincenty's formulae.

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
