{% set name = "pygc" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygc-{{ version }}.tar.gz
  sha256: 1c54f6de51172b991d877de6e14375304696abce0c7c3cf7454b267f52f9f715

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - pygc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/pygc
  license: MIT
  license_file: LICENSE
  summary: Great Circle calculations in Python using Vincenty's formulae.

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
