{% set version = "1.2.1" %}

package:
  name: pygc
  version: {{ version }}

source:
  fn: pygc-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/pygc/archive/{{ version }}.tar.gz
  sha256: 7397a6233c0ec9d4c4e5666d9ddad7a5a9af68e89401f78e3c276520652e611d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - pygc

about:
  home: https://github.com/axiom-data-science/pygc
  license: MIT
  license_file: LICENSE
  summary: "Great Circle calculations in Python using Vincenty's formulae."

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
