{% set version = "1.3.0" %}

package:
  name: pygc
  version: {{ version }}

source:
  fn: pygc-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/pygc/archive/{{ version }}.tar.gz
  sha256: 1f19b55472d342717975ac45467729cb3910d656b7161619151bbe9f577c16c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - pygc

about:
  home: https://github.com/axiom-data-science/pygc
  license: MIT
  license_file: LICENSE
  summary: Great Circle calculations in Python using Vincenty's formulae.

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
