travis:
  secure:
    BINSTAR_TOKEN: PpiWBJ7Zkxn93yv+B5oSeANIfLlCJ7Ljsl2xUbfmHdU1qIDfBni9hB50ko2JA/1g4QBv9TmYLPQQaIDtbwI5qHyYKe4iTOgcMYlNwpKzQphUn+IXO7Sq6HBFqHMR1Neo/BwMEBiZXIJY/BXO+cU4tC9VyODrKeKN1xoPRE413dAso3UlVgyg1qgEZqw91A10bENbWkv1EY8MhlB3FpIi0ULu2grkbZzk8+qyMuBs7bzrYY0Ec9SsmJ0lB0Zm3Vfw8Xn4chTA2tp9weWRelIOtJCWKJYSBGqMXMwQ1y/q2yhw9HD+BH7uBvnO/joKwpiaXsl+eix/Rm8wNK/kZRRjyji2iwdFQfpbZMO8/6+2G1pbxV1VIHty5aaO8y2TeQzS82h8tO0s0Sgvt+mQlh0CknEOItwbzEEYN4B2KbFb1tzYGbBguNfodxlQcqMO0qtmZps8GmIQiwCbV5ddG3CaWS8dHmrRfHOFqtwlIZ2Rs7enEH2uMZPJ2ejZgPFSY6RecALJCA66VQ195Aqpepatla+0WL2PRboOIpb4tGxuvhYgPuGOcLEfMmg0I+bpLfe09Qz7zS5WNMpM6EKLVChTo1+AlwYa1rqkcWQxUZZOr/B+gFnbrW2DAIdoZVX1TqMczKFzbLjzoTpxAQQPnP5yEPb6aBfTLn8inWHisxIpuks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
