travis:
  secure:
    BINSTAR_TOKEN: IWPYfXPL23iRXYRuNvo4wxCSIvnXiCK7GT+5q1VGKVx9dka+KT+ypFv+6xb+eVX8ePPThjTv06V4ZMJd7EXPDJ7KgvY8jWR8Ts8kwpaYhVY7CtSsxQPmoiCvljvsDzcyVNZvED8OE3HWqagCfetclLTgpb7gtkpZp6WO8IHdoQamqlj6Irffkxui/tjqpkhnaSy9TbntAGYI1KngIfD7xSd0V2fygQe4WAvbI/OjRooUYaH9utQqLXZeXPa1PCZ+JPsKdgLOftEdM4tpNFxMyJ9fPYsfBK83JIhFgrAAEOi1gTwuMWh/QIcbzuVFU4Z5I/qEE/SapxoQkEjzulQ4DYR50kuo1M3LIschUE1zWD56fBY2alM7F5dhKm6Nw95Uiw24NtCUV6CDq591ETyluhM5bfgSEmsrQAirDyE3y3y2zyD5VetDbNwK6dsSqjPPqdGP51mFMNgBmRKbrwT1ZfFwAAgFhFF4b6+LUmXEMJe+BD9GFpt2xuChNeRt1p5Zcmhhpv0ccL/ceEAD8tENDMrOe1ddC6lH0FD+yK9Bks0fixULgxXSDj7fsoh01GuuPPLaYN+0Hv4+0nzvuyEfFSMJ4OCgwLQm6MhrJZLKVtUxCxYv9TQtYXLFo99hX2Q5DsfEW9cIO45gwPzNWFCzvxLZUexYfisB+lFTYTKttNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
